version: "3"
services:
  cool-web-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - notUsed:/home/node/app/node_modules
      - .:/home/node/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - notUsed:/home/node/app/node_modules
      - .:/home/node/app
    command: ["npm", "run", "test"]
volumes:
  notUsed:
