FROM node:16-alpine

RUN mkdir -p /home/node/app && chown node:node /home/node/app

WORKDIR /home/node/app

USER node

COPY --chown=node:node package.json ./

RUN npm install

COPY --chown=node:node . .

CMD ["npm", "start"]
